### ISSUE TITLE
EVE texture not readable

### ISSUE THREAD

**Issue by UnanimousCoward** [ducakar/img2dds#1]
Hi

Used this in 1.0 to convert mod textures to DDS. All seems fine, except that I repeatedly get the following exception about a texture from EVE in the logs: 
`UnityException: Texture 'BoulderCo/Clouds/Textures/kerbin1' is not readable, the texture memory can not be accessed from scripts. You can make the texture readable in the Texture Import Settings.`

Should be marked as readable by your script, shouldn't it? Logs are here if they're any use:
https://www.dropbox.com/sh/0x42ih4d0ptkmtj/AADxXhmKjamvZ3Vm-WckjqFTa?dl=0

**Comment by ducakar** [comment]
The DDS loader that is now built into KSP doesn't support "readability" AFAIK. Those textures need to remain in PNG format. I'll update img2dds in the following days.

The readability tagging used by this script only worked for TextureReplacer's internal DDS loader that was not present in the final releases, only in my personal ones :) . DDSLoader determined readability by looking into ATM's configuration files.
