### ISSUE TITLE
Error trying to run converter

### ISSUE THREAD

**Issue by svm420** [ducakar/img2dds#4]
Hello. I am trying to use the converter on Linux Mint 17.1 64 bit and am getting this error that I really don't know how to solve. i am posting hoping you could steer me in the right direction so I can fix my problem. Please let me know what information you need from me. Thanks!

FAILED to convert ./GameData/Kontainers/Assets/Kontainer_02.png
./img2dds/linux64/img2dds: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/mcfadds2/IMG_Converter/img2dds/linux64/libfreeimage.so.3)

**Comment by ducakar** [comment]
Which GCC do you have installed? Try GGC 4.9. If it doesn't work, install all dependencies and compile it yourself.

**Comment by svm420** [comment]
Well not sure what changed in the past 2 weeks, but it is working now. Maybe I updated to 4.9 and didn't know IDK I am very new to Linux and even newer to coding so I don't really know much about compiling. Just glad it is working know really appreciate the program. Thanks again for the help.
